# BBTravis CI configuration file

language: python

# Available Python versions:
python:
  - "3.8"
label_mapping:
  TWISTED: tw
  SQLALCHEMY: sqla
  SQLALCHEMY_MIGRATE: sqlam
  latest: l
  python: py
  TESTS: t
  DB_TYPE: db
  WORKER_PYTHON: wp
env:
  global:
  - BUILDBOT_TEST_DB_URL=sqlite://
  - NUM_CPU=700m
  - MEMORY_SIZE=1G
  - CHROME_BIN=/usr/bin/chromium-browser
  matrix:
  - TWISTED=latest SQLALCHEMY=latest TESTS=coverage

  # add js tests in separate job. Start it early because it is quite long
  - TWISTED=latest SQLALCHEMY=latest TESTS=js_build NUM_CPU=2 MEMORY_SIZE=2G
  - TWISTED=latest SQLALCHEMY=latest TESTS=js_unit NUM_CPU=2 MEMORY_SIZE=2G
  - TWISTED=latest SQLALCHEMY=latest TESTS=smokes NUM_CPU=4 MEMORY_SIZE=4G

  - TWISTED=17.9.0 SQLALCHEMY=latest TESTS=trial

  - TWISTED=latest SQLALCHEMY=latest TESTS=interop WORKER_PYTHON=3.7
  - TWISTED=latest SQLALCHEMY=latest TESTS=interop WORKER_PYTHON=3.6
  - TWISTED=latest SQLALCHEMY=latest TESTS=interop WORKER_PYTHON=3.5

  # Configuration when SQLite database is persistent between running tests
  # (by default in other tests in-memory SQLite database is used which is
  # recreated for each test).
  # Helps to detect issues with incorrect database setup/cleanup in tests.
  - TWISTED=latest SQLALCHEMY=latest TESTS=trial BUILDBOT_TEST_DB_URL=sqlite:////tmp/test_db.sqlite DB_TYPE=sqlite
  # Configuration that runs tests with real MySQL database (TODO does not work yet with our docker image)
  - TWISTED=latest SQLALCHEMY=latest TESTS=trial BUILDBOT_TEST_DB_URL=mysql+mysqldb://travis@127.0.0.1/bbtest DB_TYPE=mysql

  # innodb tests takes 20min probably because of docker aufs.
  # travis images provides much faster innodb so we keep these test there until we implement ramfs based
  # mysql installation
  # - TWISTED=latest SQLALCHEMY=latest TESTS=trial BUILDBOT_TEST_DB_URL=mysql+mysqldb://travis@127.0.0.1/bbtest?storage_engine=InnoDB

  # Configuration that runs tests with real PostgreSQL database with pg8000 and psycopg2 drivers
  # psycopg2 uses Peer Authentication which is configured in the dockerfile, while pg8000 use md5 auth with dummy password
  #- TWISTED=latest SQLALCHEMY=latest TESTS=trial BUILDBOT_TEST_DB_URL=postgresql+psycopg2:///bbtest
  #- TWISTED=latest SQLALCHEMY=latest TESTS=trial 'BUILDBOT_TEST_DB_URL=postgresql+pg8000:///bbtest?user=buildbot&password=x'

  # Test different versions of SQLAlchemy
  - TWISTED=17.9.0 SQLALCHEMY=1.1.0 TESTS=trial
  - TWISTED=17.9.0 SQLALCHEMY=latest TESTS=trial

  # Tests for the worker on old versions of twisted.
  - TWISTED=17.9.0 SQLALCHEMY=latest TESTS=trial_worker

matrix:
  fast_finish: true
  include:
    # flake8, isort, pylint, docs first as they're more likely to find issues
    - python: "3.8"
      env: TWISTED=latest SQLALCHEMY=latest TESTS=flake8
    - python: "3.8"
      env: TWISTED=latest SQLALCHEMY=latest TESTS=isort
    - python: "3.8"
      env: TWISTED=latest SQLALCHEMY=latest TESTS=pylint NUM_CPU=2 MEMORY_SIZE=4G
    - python: "3.8"
      env: TWISTED=latest SQLALCHEMY=latest TESTS=docs

    - python: "3.6"
      env: TWISTED=latest SQLALCHEMY=latest TESTS=trial
    - python: "3.7"
      env: TWISTED=latest SQLALCHEMY=latest TESTS=trial
    - python: "3.8"
      env: TWISTED=latest SQLALCHEMY=latest TESTS=trial

    - python: "3.8"
      env: TWISTED=latest SQLALCHEMY=latest TESTS=interop WORKER_PYTHON=2.7

    # keep worker supported on py2.7
    - python: "2.7"
      env: TWISTED=latest SQLALCHEMY=latest TESTS=trial_worker

# Dependencies installation commands
install:
  - pip install -U pip
  - condition: TESTS not in ("smokes", "trial_worker")
    cmd: pip install -r requirements-ci.txt
  - condition: TESTS == "trial_worker"
    cmd: pip install -r requirements-ciworker.txt
  - condition: TESTS == "docs"
    cmd: pip install -r requirements-cidocs.txt
  - condition: '"sqlite" not in BUILDBOT_TEST_DB_URL'
    cmd: pip install -r requirements-cidb.txt
  - condition: TESTS == "interop"
    cmd: |
      virtualenv -p python$WORKER_PYTHON /tmp/workerenv
      /tmp/workerenv/bin/pip install -e worker
  - |
      # pip installs for backward compat
      set -e
      if [ $TWISTED = trunk ]; then
          pip install git+https://github.com/twisted/twisted
      fi
      if [ $TWISTED != latest -a  $TWISTED != trunk ]; then pip install Twisted==$TWISTED ; fi
      if [ $SQLALCHEMY != latest ]; then pip install sqlalchemy==$SQLALCHEMY; fi
  - step: !ShellCommand
        command: "pip check"
        warnOnFailure: True
        flunkOnFailure: False
        haltOnFailure: False
        name: "pip check"
    title: "pip check"

before_script:
  # create real database for tests
  - condition: '"mysql" in BUILDBOT_TEST_DB_URL'
    cmd: sudo /etc/init.d/mysql start
  - condition: '"postgresql" in BUILDBOT_TEST_DB_URL'
    cmd: |
        sudo /etc/init.d/postgresql start
        # for pg8000 driver we can't use peer authentication or empty password, so set a dummy password
        # This also serves as a way to wait that the database is ready
        while ! psql -d bbtest -c 'ALTER USER "buildbot" WITH PASSWORD '"'x'"';' ; do sleep 1 ; done

# Tests running commands
script:
  # make frontend_install_tests takes 17 min, so we only do it post submit
  - title: frontend build tests
    condition: TESTS == "js_build" and TRAVIS_PULL_REQUEST
    cmd: make frontend

  - title: full frontend tests
    condition: TESTS == "js_build" and not TRAVIS_PULL_REQUEST
    cmd: make frontend_install_tests

  - title: frontend unit tests
    condition: TESTS == "js_unit"
    cmd: make frontend_tests_headless

  - title: master and worker tests
    condition: TESTS == "trial"
    cmd: trial  --reporter=text --rterrors buildbot.test buildbot_worker.test

  - title: interop tests
    condition: TESTS == "interop"
    cmd: SANDBOXED_WORKER_PATH=/tmp/workerenv/bin/buildbot-worker coverage run --rcfile=.coveragerc $(which trial) --reporter=text --rterrors buildbot.test.integration.interop

  - title: worker tests
    condition: TESTS == "trial_worker"
    cmd: trial  --reporter=text --rterrors buildbot_worker.test

  # run tests under coverage for latest only (it's slower..)
  - title: coverage tests
    condition: TESTS == "coverage"
    cmd: coverage run --rcfile=.coveragerc $(which trial) --reporter=text --rterrors buildbot.test buildbot_worker.test

  # Run additional tests in their separate job
  - title: pylint
    condition: TESTS == "pylint"
    cmd: make pylint

  - title: flake8
    condition: TESTS == "flake8"
    cmd: make flake8

  - title: isort
    condition: TESTS == "isort"
    cmd: isort --check -df `git ls-files |grep '.py$'`

  # Build documentation
  - title: docs
    condition: TESTS == "docs"
    cmd: make docs

  # Run spell checker on documentation
  - title: spelling
    condition: TESTS == "docs"
    cmd: make -C master/docs SPHINXOPTS=-W spelling

  # Runs Sphinx' external link checker only on post submit build (it is too unstable)
  - title: linkcheck
    condition: TESTS == "docs" and not TRAVIS_PULL_REQUEST
    cmd: make -C master/docs SPHINXOPTS=-q linkcheck

  - title: maketarballs
    condition: TESTS == "smokes"
    cmd: make tarballs

  - title: protractor tests
    condition: TESTS == "smokes"
    cmd: ./common/smokedist.sh whl

  - title: tarballs protractor tests
    condition: TESTS == "smokes" and not TRAVIS_PULL_REQUEST
    cmd: ./common/smokedist.sh tar.gz

notifications:
  email: false

after_script:
  - |
      # codecov
      if [ $TESTS = coverage ]; then CODECOV_TOKEN="b80c80d7-689d-46d7-b1aa-59168bb4c9a9" codecov; fi
  # List installed packages along with their versions.
  - "pip list"

sudo: false
branches:
  # Only build main-line branches.
  only:
    - master
    - eight
git:
  depth: 300
