language: node_js
sudo: false
dist: trusty
addons:
  chrome: beta
node_js:
  - "4.5"
  - "6.10"
  - "7.10"

before_install:
  - yarn global add gulp

script:
  - 'export CHROME_BIN=google-chrome-beta'
  - xvfb-run ./test.sh
