#%RAML 1.0 DataType
description: |
    This resource type describes a project.

    Update Methods
    --------------

    All update methods are available as attributes of ``master.data.updates``.

    .. py:class:: buildbot.data.projects.Project

        .. py:method:: updateBuilderList(masterid, builderNames)

            :param integer masterid: this master's master ID
            :param list builderNames: list of names of currently-configured builders (unicode strings)
            :returns: Deferred

            Record the given builders as the currently-configured set of builders on this master.
            Masters should call this every time the list of configured builders changes.


properties:
    projectid:
        description: the ID of this project
        type: integer
    name:
        description: project name
        type: identifier
    slug:
        description: project slug
        type: identifier
    description?:
        description: description of the project
        type: string
type: object
