#%RAML 1.0 DataType
properties:
    path:
        description: ''
        type: string
    plural:
        description: ''
        type: string
    type:
        description: ''
        type: string
    type_spec:
        description: ''
        type: object
type: object
