#!/bin/bash
echo $(dirname $0)
cd $(dirname $0)
cd ..
find master slave -name '*.pyc' -exec rm \{} \; || exit 1
# excludes both test suites
python docs/epyrun -o docs/reference --exclude="buildbot\\.test" --exclude="buildslave\\.test" buildbot buildslave
