#%RAML 1.0 DataType
properties:
  builderid:
    description: ''
    type: integer
  buildrequestid:
    description: ''
    type: integer
  buildsetid:
    description: ''
    type: integer
  claimed:
    description: ''
    type: boolean
  claimed_at?:
    description: ''
    type: date
  claimed_by_masterid?:
    description: ''
    type: integer
  complete:
    description: ''
    type: boolean
  complete_at?:
    description: ''
    type: date
  priority:
    description: ''
    type: integer
  results?:
    description: ''
    type: integer
  submitted_at:
    description: ''
    type: date
  waited_for:
    description: ''
    type: boolean
type: object
