#%RAML 1.0 DataType
properties:
  builderid:
    description: ''
    type: integer
  description?:
    description: ''
    type: string
  masterids[]:
    description: ''
    type: integer
  name:
    description: ''
    type: identifier
  tags[]:
    description: ''
    type: string
type: object
