#%RAML 1.0 DataType
properties:
  builderid:
    description: ''
    type: integer
  buildid:
    description: ''
    type: integer
  buildrequestid:
    description: ''
    type: integer
  buildslaveid:
    description: ''
    type: integer
  complete:
    description: ''
    type: boolean
  complete_at?:
    description: ''
    type: date
  masterid:
    description: ''
    type: integer
  number:
    description: ''
    type: integer
  properties?:
    description: ''
    type: sourcedproperties
  results?:
    description: ''
    type: integer
  started_at:
    description: ''
    type: date
  state_string:
    description: ''
    type: string
type: object
