#%RAML 1.0 DataType
properties:
  all_fields[]:
    description: ''
    type: object
  builder_names[]:
    description: ''
    type: identifier
  button_name:
    description: ''
    type: string
  label:
    description: ''
    type: string
  name:
    description: ''
    type: identifier
type: object
