#%RAML 1.0 DataType
properties:
  complete:
    description: ''
    type: boolean
  logid:
    description: ''
    type: integer
  name:
    description: ''
    type: string
  num_lines:
    description: ''
    type: integer
  slug:
    description: ''
    type: identifier
  stepid:
    description: ''
    type: integer
  type:
    description: ''
    type: identifier
type: object
