#%RAML 1.0 DataType
properties:
  active:
    description: ''
    type: boolean
  last_active:
    description: ''
    type: date
  masterid:
    description: ''
    type: integer
  name:
    description: ''
    type: string
type: object
