#%RAML 1.0 DataType
properties:
  branch?:
    description: ''
    type: string
  codebase:
    description: ''
    type: string
  created_at:
    description: ''
    type: date
  patch?:
    description: ''
    type: patch
  project:
    description: ''
    type: string
  repository:
    description: ''
    type: string
  revision?:
    description: ''
    type: string
  ssid:
    description: ''
    type: integer
type: object
